package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTAddSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=070be7f5608465547beb4ab7b696f057 (do not edit this line) */
