/* Generated By:JJTree: Do not edit this line. ASTArrayAutoCreation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTArrayAutoCreation extends SimpleNode {
  public ASTArrayAutoCreation(int id) {
    super(id);
  }

  public ASTArrayAutoCreation(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5018ca09b5d36f1770726c5a9255869 (do not edit this line) */
