package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTAttributeAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAttributeAccess extends SimpleNode {
  public ASTAttributeAccess(int id) {
    super(id);
  }

  public ASTAttributeAccess(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=635f4467b75662edfc63efd8f747a04f (do not edit this line) */
