package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTArrayValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayValue extends SimpleNode {
  public ASTArrayValue(int id) {
    super(id);
  }

  public ASTArrayValue(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d66467ebe1e5a161806f4b7bdd1ce15a (do not edit this line) */
