package uk.ac.cam.crsid.Parallang.Parser;

import uk.ac.cam.crsid.Parallang.TypeChecking.Type;

/* Generated By:JJTree: Do not edit this line. ASTBlockRecv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBlockRecv extends SimpleNode {
  public ASTBlockRecv(int id) {
    super(id);
  }

  public ASTBlockRecv(ParallogParser p, int id) {
    super(p, id);
  }

  public boolean isDecl = false;
  public Type expectedType = null;

  public void setVarToken(Token tok) {
    isDecl = (tok != null) && !tok.image.isEmpty();
  }

}
/* JavaCC - OriginalChecksum=1cb5a72575bca91119b45827c5804f42 (do not edit this line) */
