package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTCallFunArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCallFunArguments extends SimpleNode {
  public ASTCallFunArguments(int id) {
    super(id);
  }

  public ASTCallFunArguments(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f57d52232e7353a308b48e0957bc05b (do not edit this line) */
