package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTCallArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCallArguments extends SimpleNode {
  public ASTCallArguments(int id) {
    super(id);
  }

  public ASTCallArguments(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=171d81d560e18d5a4404df38b9cc3c37 (do not edit this line) */
