package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTConditional.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditional extends SimpleNode {
  public ASTConditional(int id) {
    super(id);
  }

  public ASTConditional(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46e6940c876e7465785d891d672a863a (do not edit this line) */
