package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTCode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCode extends SimpleNode {
  public ASTCode(int id) {
    super(id);
  }

  public ASTCode(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a81c34b38a5c9655e7dc4a4aa775253 (do not edit this line) */
