package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTDivisionMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDivisionMult extends SimpleNode {
  public ASTDivisionMult(int id) {
    super(id);
  }

  public ASTDivisionMult(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3cb6cbd661f18cc3eaf9c0de990a10f3 (do not edit this line) */
