package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTDefnArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDefnArguments extends SimpleNode {
  public ASTDefnArguments(int id) {
    super(id);
  }

  public ASTDefnArguments(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4decd2e34311b2bff173a9b29a6c627a (do not edit this line) */
