package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42e779b42e01b540a36f6c48b22659d3 (do not edit this line) */
