package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTEqNeq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEqNeq extends SimpleNode {
  public ASTEqNeq(int id) {
    super(id);
  }

  public ASTEqNeq(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3473b37c83bb27cb2c0fa19663c6709 (do not edit this line) */
