package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTForLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTForLoop extends SimpleNode {
  public ASTForLoop(int id) {
    super(id);
  }

  public ASTForLoop(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61463960479333ce7f96574583d05384 (do not edit this line) */
