package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTFunDefnArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunDefnArguments extends SimpleNode {
  public ASTFunDefnArguments(int id) {
    super(id);
  }

  public ASTFunDefnArguments(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f4feb022b6e532c52f173ad14f0e72e3 (do not edit this line) */
