package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTGLGeLe.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGLGeLe extends SimpleNode {
  public ASTGLGeLe(int id) {
    super(id);
  }

  public ASTGLGeLe(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a552ca8333c985969aa17db7c9591065 (do not edit this line) */
