/* Generated By:JJTree: Do not edit this line. ASTGet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTGet extends SimpleNode {
  public ASTGet(int id) {
    super(id);
  }

  public ASTGet(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af9fa4cefb16b4ca1e3514c0bea349b3 (do not edit this line) */
