/* Generated By:JJTree: Do not edit this line. ASTIndices.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTIndices extends SimpleNode {
  public ASTIndices(int id) {
    super(id);
  }

  public ASTIndices(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85a84541d6ee9237c3f0aefda963c7f3 (do not edit this line) */
