/* Generated By:JJTree: Do not edit this line. ASTLogical.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTLogical extends SimpleNode {
  public ASTLogical(int id) {
    super(id);
  }

  public ASTLogical(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d542d8ea9030002efd5aeb93f58247f7 (do not edit this line) */
