package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTLogicalAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalAnd extends SimpleNode {
  public ASTLogicalAnd(int id) {
    super(id);
  }

  public ASTLogicalAnd(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a0a0c11dc6e70908c7a85b5f46d6a07 (do not edit this line) */
