/* Generated By:JJTree: Do not edit this line. ASTLen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTLen extends SimpleNode {
  public ASTLen(int id) {
    super(id);
  }

  public ASTLen(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=336a4f382ca42d5f56bbc9dc08d97ec7 (do not edit this line) */
