package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTLogicalOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalOr extends SimpleNode {
  public ASTLogicalOr(int id) {
    super(id);
  }

  public ASTLogicalOr(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eee2b465a7a3bc486c151bf6565114ad (do not edit this line) */
