package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTListValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTListValue extends SimpleNode {
  public ASTListValue(int id) {
    super(id);
  }

  public ASTListValue(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e0096ad2aa7b3f90be0204b2d179b5f (do not edit this line) */
