/* Generated By:JJTree: Do not edit this line. ASTmyY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTmyY extends SimpleNode {
  public ASTmyY(int id) {
    super(id);
  }

  public ASTmyY(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=884acad1d4563483c78a40ded8482973 (do not edit this line) */
