/* Generated By:JJTree: Do not edit this line. ASTmyX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTmyX extends SimpleNode {
  public ASTmyX(int id) {
    super(id);
  }

  public ASTmyX(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8a8d8696a99ee1c5d8b4a457434efb0 (do not edit this line) */
