/* Generated By:JJTree: Do not edit this line. ASTMathOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTMathOp extends SimpleNode {
  public ASTMathOp(int id) {
    super(id);
  }

  public ASTMathOp(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7569db918f781096e389970a5f419bfc (do not edit this line) */
