/* Generated By:JJTree: Do not edit this line. ASTnumRows.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTnumRows extends SimpleNode {
  public ASTnumRows(int id) {
    super(id);
  }

  public ASTnumRows(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4582eb210d078aae60fd39cb341a552 (do not edit this line) */
