package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTNegation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNegation extends SimpleNode {
  public ASTNegation(int id) {
    super(id);
  }

  public ASTNegation(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85ff8087172cd5071532cb306d2641b9 (do not edit this line) */
