/* Generated By:JJTree: Do not edit this line. ASTnumCols.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTnumCols extends SimpleNode {
  public ASTnumCols(int id) {
    super(id);
  }

  public ASTnumCols(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=199e4cbab346cd66798a5033b01b77d5 (do not edit this line) */
