package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNumber extends SimpleNode {
  private long number;
  private boolean isInfinity = false;

  public void setNumber(long n) {
    number = n;
  }
  public long getNumber() {
    return number;
  }

  public void setInfinity(boolean isInfinity ) { this.isInfinity = isInfinity; }

  public String toString() {
    return "Number: " + number;
  }

  public ASTNumber(int id) {
    super(id);
  }

  public ASTNumber(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70b0f90b719e40e9cf5710f9d8dd3b8c (do not edit this line) */
