package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTOptionalValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOptionalValue extends SimpleNode {
  public enum Option {
    NONE,
    SOME
  }
  public Option option;
  public ASTOptionalValue(int id) {
    super(id);
  }

  public ASTOptionalValue(ParallogParser p, int id) {
    super(p, id);
  }

  public void setOption(String optionToken) {
    switch (optionToken) {
      case "none": option = Option.NONE; break;
      case "some": option = Option.SOME; break;
      default: throw new RuntimeException("Unknown option token: " + optionToken);
    }
  }

}
/* JavaCC - OriginalChecksum=9958b394efd6580e5d91f6a37f338d6e (do not edit this line) */
