/* Generated By:JJTree: Do not edit this line. ASTOptExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTOptExpr extends SimpleNode {
  public ASTOptExpr(int id) {
    super(id);
  }

  public ASTOptExpr(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5ec9882d61b08fb385293d2a6649d807 (do not edit this line) */
