/* Generated By:JJTree: Do not edit this line. ASTPrintln.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTPrintln extends SimpleNode {
  public ASTPrintln(int id) {
    super(id);
  }

  public ASTPrintln(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2581d4bc833a95c6a561e00ab03891ef (do not edit this line) */
