package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTParen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParen extends SimpleNode {
  public ASTParen(int id) {
    super(id);
  }

  public ASTParen(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1261404ff79e01f238d388aa7ffde751 (do not edit this line) */
