package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTParameterTypes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameterTypes extends SimpleNode {
  public ASTParameterTypes(int id) {
    super(id);
  }

  public ASTParameterTypes(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6fb06665a492f6925b5a697da5cee6e7 (do not edit this line) */
