/* Generated By:JJTree: Do not edit this line. ASTRValueIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTRValueIndex extends SimpleNode {
  public ASTRValueIndex(int id) {
    super(id);
  }

  public ASTRValueIndex(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd752f4674a3ba5fda759ffdc8ec7608 (do not edit this line) */
