/* Generated By:JJTree: Do not edit this line. ASTSoloExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTSoloExpression extends SimpleNode {
  public ASTSoloExpression(int id) {
    super(id);
  }

  public ASTSoloExpression(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe0fe2a958c9ac35e4d50c29cbdf31b6 (do not edit this line) */
