package uk.ac.cam.crsid.Parallang.Parser;

import uk.ac.cam.crsid.Parallang.TypeChecking.Type;

/* Generated By:JJTree: Do not edit this line. ASTSend.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSend extends SimpleNode {
  public ASTSend(int id) {
    super(id);
  }

  public ASTSend(ParallogParser p, int id) {
    super(p, id);
  }

  public Type expectedType = null;

}
/* JavaCC - OriginalChecksum=be7d5733887c593e1b79a22924566771 (do not edit this line) */
