package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTStructureDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStructureDecl extends SimpleNode {
  public ASTStructureDecl(int id) {
    super(id);
  }

  public ASTStructureDecl(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b87693d551419d393eec3142227e2984 (do not edit this line) */
