/* Generated By:JJTree: Do not edit this line. ASTStructValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTStructValue extends SimpleNode {
  public ASTStructValue(int id) {
    super(id);
  }

  public ASTStructValue(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5117261722cdad8d1584d390dd64c39 (do not edit this line) */
