package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {

  public enum Type {
    ARRAY,
    INT,
    OPTION,
    STRUCT,
    UNIT
  }

  Type nodeType;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(ParallogParser p, int id) {
    super(p, id);
  }

  public void setType(String strType) {
    switch (strType) {
      case "array": nodeType = Type.ARRAY; break;
      case "option": nodeType = Type.OPTION; break;
      case "int": nodeType = Type.INT; break;
      case "struct": nodeType = Type.STRUCT; break;
      case "unit": nodeType = Type.UNIT; break;
      default: throw new RuntimeException("Unknown type: " + strType);
    }
  }

  public Type getType() { return nodeType; }

  public String toString() {
    return "Type: " + nodeType;
  }

}
/* JavaCC - OriginalChecksum=2a12f7e7dd7bf65eaf46d0942644f100 (do not edit this line) */
