package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTSendTarget.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTarget extends SimpleNode {

  public enum Target {
    WORKER,
    BROADCAST,
    BROADCAST_ROW,
    BROADCAST_COL,
    EXTERNAL
  }

  public Target target;
  public ASTTarget(int id) {
    super(id);
  }

  public ASTTarget(ParallogParser p, int id) {
    super(p, id);
  }

  public void setTarget(String tokenTarget) {
    switch (tokenTarget) {
      case "worker": target = Target.WORKER; break;
      case "broadcast": target = Target.BROADCAST; break;
      case "broadcast_row": target = Target.BROADCAST_ROW; break;
      case "broadcast_col": target = Target.BROADCAST_COL; break;
      case "external": target = Target.EXTERNAL; break;
      default: throw new RuntimeException("Unknown token: " + tokenTarget);
    }
  }

  public String toString() {
    return "Target: " + target;
  }
}
/* JavaCC - OriginalChecksum=baf77dda02b45ee531a922b372c17436 (do not edit this line) */
