package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTTryRecv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTryRecv extends SimpleNode {
  public ASTTryRecv(int id) {
    super(id);
  }

  public ASTTryRecv(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e36c39bdace8d261dbc7394b18db3ffa (do not edit this line) */
