package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTUnary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnary extends SimpleNode {
  public ASTUnary(int id) {
    super(id);
  }

  public ASTUnary(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6591f7b82ec7e04eb0561c4ffda5e72 (do not edit this line) */
