package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTUnaryOrParen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryOrParen extends SimpleNode {
  public ASTUnaryOrParen(int id) {
    super(id);
  }

  public ASTUnaryOrParen(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1e6571b0d9d0aa70426add000aad211 (do not edit this line) */
