/* Generated By:JJTree: Do not edit this line. ASTUnitValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.cam.crsid.Parallang.Parser;

public
class ASTUnitValue extends SimpleNode {
  public ASTUnitValue(int id) {
    super(id);
  }

  public ASTUnitValue(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf9dbc3cc3822de467ebc4996b1ff54d (do not edit this line) */
