package uk.ac.cam.crsid.Parallang.Parser;

/* Generated By:JJTree: Do not edit this line. ASTWhileLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileLoop extends SimpleNode {
  public ASTWhileLoop(int id) {
    super(id);
  }

  public ASTWhileLoop(ParallogParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61d4b3645b74fbc2f06e4111d4a48ea2 (do not edit this line) */
