/* Generated By:JavaCC: Do not edit this line. ParallogParserTreeConstants.java Version 5.0 */
package uk.ac.cam.crsid.Parallang.Parser;

public interface ParallogParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTTYPE = 1;
  public int JJTCODE = 2;
  public int JJTFUNCTION = 3;
  public int JJTSTRUCTUREDECL = 4;
  public int JJTDEFNARGUMENTS = 5;
  public int JJTVOID = 6;
  public int JJTLEN = 7;
  public int JJTPRINTLN = 8;
  public int JJTDECLARATION = 9;
  public int JJTSEND = 10;
  public int JJTTARGET = 11;
  public int JJTBLOCKRECV = 12;
  public int JJTTRYRECV = 13;
  public int JJTCONDITIONAL = 14;
  public int JJTIF = 15;
  public int JJTELSE = 16;
  public int JJTSOLOEXPRESSION = 17;
  public int JJTFORLOOP = 18;
  public int JJTOPTEXPR = 19;
  public int JJTWHILELOOP = 20;
  public int JJTRETURN = 21;
  public int JJTCALL = 22;
  public int JJTARRAYVALUE = 23;
  public int JJTARRAYAUTOCREATION = 24;
  public int JJTCALLARGUMENTS = 25;
  public int JJTOPERATOR = 26;
  public int JJTASSIGNMENT = 27;
  public int JJTLOGICALOR = 28;
  public int JJTLOGICALAND = 29;
  public int JJTMATHOP = 30;
  public int JJTEQNEQ = 31;
  public int JJTNEGATION = 32;
  public int JJTATTRIBUTEACCESS = 33;
  public int JJTINDEX = 34;
  public int JJTSTRUCTVALUE = 35;
  public int JJTOPTIONALVALUE = 36;
  public int JJTINDICES = 37;
  public int JJTNUMBER = 38;
  public int JJTNAME = 39;
  public int JJTMYX = 40;
  public int JJTMYY = 41;
  public int JJTNUMROWS = 42;
  public int JJTNUMCOLS = 43;
  public int JJTUNITVALUE = 44;
  public int JJTGET = 45;


  public String[] jjtNodeName = {
    "Start",
    "Type",
    "Code",
    "Function",
    "StructureDecl",
    "DefnArguments",
    "void",
    "Len",
    "Println",
    "Declaration",
    "Send",
    "Target",
    "BlockRecv",
    "TryRecv",
    "Conditional",
    "If",
    "Else",
    "SoloExpression",
    "ForLoop",
    "OptExpr",
    "WhileLoop",
    "Return",
    "Call",
    "ArrayValue",
    "ArrayAutoCreation",
    "CallArguments",
    "Operator",
    "Assignment",
    "LogicalOr",
    "LogicalAnd",
    "MathOp",
    "EqNeq",
    "Negation",
    "AttributeAccess",
    "Index",
    "StructValue",
    "OptionalValue",
    "Indices",
    "Number",
    "Name",
    "myX",
    "myY",
    "numRows",
    "numCols",
    "UnitValue",
    "Get",
  };
}
/* JavaCC - OriginalChecksum=b1a9752bc0fcfb8ea5f48add87763bc0 (do not edit this line) */
